<div id="dataViz">
         <table id="stackHeapTable">
           <tbody><tr>
             <td id="stack_td">
               <div id="globals_area">
                 <div id="stackHeader">Frames</div>
               <div class="stackFrame" id="v1__globals"><div id="v1__globals_header" class="stackFrameHeader">Global frame</div><table class="stackFrameVarTable" id="v1__global_table"><tr class="variableTr" id="v1__global__listSum_tr"><td class="stackFrameVar">listSum</td><td class="stackFrameValue"><div class="stack_pointer" id="v1__global__listSum">&nbsp;</div></td></tr><tr class="variableTr" id="v1__global__myList_tr"><td class="stackFrameVar">myList</td><td class="stackFrameValue"><div class="stack_pointer" id="v1__global__myList">&nbsp;</div></td></tr></table></div></div>
               <div id="stack"><div class="stackFrame" id="v1__stack0" data-frame_id="1"><div class="stackFrameHeader">listSum</div><table class="stackFrameVarTable"><tr class="variableTr" id="v1__listSum_f1__numbers_tr"><td class="stackFrameVar">numbers</td><td class="stackFrameValue"><div class="stack_pointer" id="v1__listSum_f1__numbers">&nbsp;</div></td></tr><tr class="variableTr" id="v1__listSum_f1__f_tr"><td class="stackFrameVar">f</td><td class="stackFrameValue"><span class="numberObj">1</span></td></tr><tr class="variableTr" id="v1__listSum_f1__rest_tr"><td class="stackFrameVar">rest</td><td class="stackFrameValue"><div class="stack_pointer" id="v1__listSum_f1__rest">&nbsp;</div></td></tr></table></div><div class="stackFrame highlightedStackFrame" id="v1__stack1" data-frame_id="2"><div class="stackFrameHeader">listSum</div><table class="stackFrameVarTable"><tr class="variableTr" id="v1__listSum_f2__numbers_tr"><td class="stackFrameVar">numbers</td><td class="stackFrameValue"><div class="stack_pointer" id="v1__listSum_f2__numbers">&nbsp;</div></td></tr><tr class="variableTr" id="v1__listSum_f2__f_tr"><td class="stackFrameVar">f</td><td class="stackFrameValue"><span class="numberObj">2</span></td></tr><tr class="variableTr" id="v1__listSum_f2__rest_tr"><td class="stackFrameVar">rest</td><td class="stackFrameValue"><div class="stack_pointer" id="v1__listSum_f2__rest">&nbsp;</div></td></tr></table></div></div>
             </td>
             <td id="heap_td">
               <div id="heap"><div id="heapHeader">Objects</div><table id="heapRow0" class="heapRow"><td class="toplevelHeapObject" id="toplevel_heap_object_1"><div class="heapObject" id="v1__heap_object_1"><div class="typeLabel">function</div><div class="funcObj"> listSum(numbers)</div></div></td></table><table id="heapRow1" class="heapRow"><td class="toplevelHeapObject" id="toplevel_heap_object_2"><div class="heapObject" id="v1__heap_object_2"><div class="typeLabel">tuple</div><table class="tupleTbl"><tr><td class="tupleHeader">0</td><td class="tupleHeader">1</td></tr><tr><td class="tupleElt"><span class="numberObj">1</span></td><td class="tupleElt"><div id="v1__heap_pointer_src_1">&nbsp;</div></td></tr></table></div></td><td class="toplevelHeapObject" id="toplevel_heap_object_3"><div class="heapObject" id="v1__heap_object_3"><div class="typeLabel">tuple</div><table class="tupleTbl"><tr><td class="tupleHeader">0</td><td class="tupleHeader">1</td></tr><tr><td class="tupleElt"><span class="numberObj">2</span></td><td class="tupleElt"><div id="v1__heap_pointer_src_2">&nbsp;</div></td></tr></table></div></td><td class="toplevelHeapObject" id="toplevel_heap_object_4"><div class="heapObject" id="v1__heap_object_4"><div class="typeLabel">tuple</div><table class="tupleTbl"><tr><td class="tupleHeader">0</td><td class="tupleHeader">1</td></tr><tr><td class="tupleElt"><span class="numberObj">3</span></td><td class="tupleElt"><span class="nullObj">None</span></td></tr></table></div></td></table></div>
             </td>
           </tr>
         </tbody></table>
      </div>